import research

boilerplate = """
We have generated this research helper for you

this was generated by the research.py script
"""


def title(title, type_title):
    return f"{'#'*type_title} {title} \n\n"


def text(text):
    return f"{text}\n\n"


def link(link, text):
    return f"<a href='{link}'>{text}</a>\n\n"
