import research

boilerplate = """
We have generated this research helper for you

this was generated by the https://github.com/SarangT123/research_helper script

# Results
"""


def title(title, type_title):
    return f"{'#'*type_title} {title} \n\n"


def text(text):
    return f"{text}\n\n"


def link(link, text):
    return f"<a href='{link}'>{text}</a>\n\n"


def formated(query, qword=[]):
    data = research.research(query, qword)
    google_results = data['google']
    wiki = data['wiki']
    google_titles = []
    google_links = []
    google_texts = []
    for i in google_results:
        google_titles.append(i['title'])
        google_links.append(i['link'])
        google_texts.append(i['text'])
    wiki_titles = wiki['data']
    wiki_summary = wiki['summary']
    output = boilerplate
    output += title('Google results', 1)
    for i in range(len(google_titles)):
        output += title(link(google_links[i], google_titles[i]), 2)
        output += text(google_texts[i])
    output += title('Wikkipedia results', 1)
    print(wiki_titles)

    for i in range(len(wiki_titles)):
        output += title(link(wiki_titles[i], wiki_titles[i]), 2)
        output += text(wiki_summary[i])
    return output
